#!name= Spotify (>=iOS15)
#!desc=Unlock Spotify Premium
# 仓库地址 https://github.com/app2smile/rules
# 1. 搜索界面 歌单/歌曲可以随意切换完全播放  2. 音乐库已点赞歌曲随意切换完全播放

[MITM]
hostname = %APPEND% spclient.wg.spotify.com

[Script]
Spotify-proto = type=http-response,pattern=^https:\/\/spclient\.wg\.spotify\.com\/(bootstrap\/v1\/bootstrap|user-customization-service\/v1\/customize)$,requires-body=1,binary-body-mode=1,max-size=0,script-path=https://raw.githubusercontent.com/lvtinh89/Scripting/master/Spotify-proto.js,script-update-interval=0
