#!name= Spotify (>=iOS15)
#!desc=Unlock Spotify Premium
# Địa chỉ https://github.com/app2smile/rules
# 1. Giao diện tìm kiếm Playlist/bài hát có thể chuyển đổi tùy ý và chơi trọn vẹn  
# 2. Thư viện nhạc đã thích bài hát, chuyển đổi theo ý muốn và phát nó hoàn chỉnh

[MITM]
hostname = %APPEND% spclient.wg.spotify.com

[Script]
Spotify-proto = type=http-response,pattern=^https:\/\/spclient\.wg\.spotify\.com\/(bootstrap\/v1\/bootstrap|user-customization-service\/v1\/customize)$,requires-body=1,binary-body-mode=1,max-size=0,script-path=https://raw.githubusercontent.com/lvtinh89/Scripting/master/Spotify-proto.js,script-update-interval=0
