#!name= App Spotify (>=iOS15)
#!desc=Mở khoá Spotify Premium, 27.6.2025
#!category=🎊 Spotify
# Địa chỉ https://github.com/app2smile/rules
# 1. Giao diện tìm kiếm Playlist/bài hát có thể chuyển đổi tùy ý và chơi trọn vẹn  
# 2. Thư viện nhạc đã thích bài hát, chuyển đổi theo ý muốn và phát nó hoàn chỉnh


[Header Rewrite]
# if-none-match返回304状态码
http-request ^https:\/\/(spclient\.wg\.spotify\.com|.*-spclient\.spotify\.com(:443)?)\/user-customization-service\/v1\/customize$ header-del if-none-match

[MITM]
hostname = %APPEND% spclient.wg.spotify.com, *spclient.spotify.com

[Script]
spotify-json = type=http-request,pattern=^https:\/\/(spclient\.wg\.spotify\.com|.*-spclient\.spotify\.com(:443)?)\/(artistview\/v1\/artist|album-entity-view\/v2\/album)\/,requires-body=0,script-path=https://raw.githubusercontent.com/app2smile/rules/master/js/spotify-json.js
spotify-proto = type=http-response,pattern=^https:\/\/(spclient\.wg\.spotify\.com|.*-spclient\.spotify\.com(:443)?)\/(bootstrap\/v1\/bootstrap|user-customization-service\/v1\/customize)$,requires-body=1,binary-body-mode=1,max-size=0,script-path=https://raw.githubusercontent.com/app2smile/rules/master/js/spotify-proto.js,script-update-interval=0
